import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const libre_Baskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Image Genrator App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${libre_Baskerville.className} `}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
